* in cryptroot hook, don't rely on 'udevadm settle' to wait long enough   for the cryptdevice to appear. Reimplement the busy waiting loop found   while waiting for the root file system. Patch based on work by Swâmi   Petaramesh. LP: #164044

diff --git a/debian/initramfs/cryptroot-script b/debian/initramfs/cryptroot-script
--- a/debian/initramfs/cryptroot-script
+++ b/debian/initramfs/cryptroot-script
@@ -167,17 +167,49 @@ setup_mapping()
 		activate_vg $cryptsource
 		activate_evms $cryptsource
 	fi
-	# Wait for udev to be ready, see https://launchpad.net/bugs/85640
-	if [ -x /sbin/udevadm ]; then
-		/sbin/udevadm settle --timeout=30
-	elif [ -x /sbin/udevsettle ]; then
-		/sbin/udevsettle --timeout=30
+
+	# If the encrypted source device hasn't shown up yet, give it a
+	# little while to deal with removable devices
+
+	# the following lines below have been taken from
+	# /usr/share/initramfs-tools/scripts/local, as suggested per
+	# https://launchpad.net/bugs/164044
+	if [ ! -e "$cryptsource" ] || ! /lib/udev/vol_id "$cryptsource" >/dev/null 2>&1; then
+		log_begin_msg "Waiting for encrypted source device..."
+
+		# Default delay is 180s
+		if [ -z "${ROOTDELAY}" ]; then
+			slumber=180
+		else
+			slumber=${ROOTDELAY}
+		fi
+		if [ -x /sbin/usplash_write ]; then
+			/sbin/usplash_write "TIMEOUT ${slumber}" || true
+		fi
+
+		slumber=$(( ${slumber} * 10 ))
+		while [ ! -e "${ROOT}" ] || ! /lib/udev/vol_id "${ROOT}" >/dev/null 2>&1; do
+			/bin/sleep 0.1
+			slumber=$(( ${slumber} - 1 ))
+			[ ${slumber} -gt 0 ] || break
+		done
+
+		if [ ${slumber} -gt 0 ]; then
+			log_end_msg 0
+		else
+			log_end_msg 1 || true
+		fi
+		if [ -x /sbin/usplash_write ]; then
+			/sbin/usplash_write "TIMEOUT 15" || true
+		fi
 	fi
 
-	if [ ! -e $cryptsource ]; then
-		echo "cryptsetup: Source device $cryptsource not found"
-		return 1
-	fi
+	# We've given up, but we'll let the user fix matters if they can
+	while [ ! -e "${cryptsource}" ]; do
+		echo "	Check cryptopts=source= bootarg cat /proc/cmdline"
+		echo "	or missing modules, devices: cat /proc/modules ls /dev"
+		panic -r "ALERT!  ${cryptsource} does not exist.  Dropping to a shell!"
+	done
 
 	# Prepare commands
 	if /sbin/cryptsetup isLuks $cryptsource > /dev/null 2>&1; then
