* Merge from debian unstable, version 2:1.1.3-4

diff --git a/debian/initramfs/cryptroot-hook b/debian/initramfs/cryptroot-hook
--- a/debian/initramfs/cryptroot-hook
+++ b/debian/initramfs/cryptroot-hook
@@ -26,6 +26,7 @@ get_root_device() {
 	grep -s '^[^#]' /etc/fstab | \
 	while read device mount type options dump pass; do
 		if [ "$mount" = "/" ]; then
+			device=$(canonical_device "$device") || return 0
 			echo "$device"
 			return
 		fi
@@ -91,6 +92,8 @@ get_resume_devices() {
 			fi
 		fi
 
+		device=$(canonical_device "$device") || return 0
+
 		# Weed out duplicates
 		dupe=0
 		for opt in $devices; do
@@ -145,8 +148,8 @@ get_lvm_deps() {
 
 	# We should now have a list of major,minor pairs, e.g. "3,2 3,3"
 	for dep in $deps; do
-		maj=${dep%,*}
-		min=${dep#*,}
+		maj=$(echo ${dep%,*} | sed -e "s/^[ \t]*//g")
+		min=$(echo ${dep#*,} | sed -e "s/[ \t]*$//g")
 		depnode=$(dmsetup ls | sed -n "s/\\([^ ]*\\) *($maj, $min)/\\1/p" | sed -e "s/[ \t]*$//")
 		if [ -z "$depnode" ]; then
 			continue
@@ -178,12 +181,7 @@ get_device_opts() {
 	key=$( echo $opt | cut -d " " -f3 )
 	rootopts=$( echo $opt | cut -d " " -f4- )
 
-	if [ -z "$opt" ] ; then
-		echo "cryptsetup: WARNING: Missing line in /etc/crypttab for $target" >&2
-		return 1
-	fi
-
-	if [ -z "$source" ] || [ -z "$key" ] || [ -z "$rootopts" ]; then
+	if [ -z "$opt" ] || [ -z "$source" ] || [ -z "$key" ] || [ -z "$rootopts" ]; then
 		echo "cryptsetup: WARNING: invalid line in /etc/crypttab - $opt" >&2
 		return 1
 	fi
@@ -336,6 +334,7 @@ canonical_device() {
 		return 0
 	fi
 
+	echo "cryptsetup: WARNING: failed to detect canonical device of $original" >&2
 	return 1
 }
 
@@ -359,7 +358,7 @@ add_device() {
 	fi
 
 	# Check that it is a node under /dev/mapper/
-	nodes=$(canonical_device "$nodes") || return 0
+	# nodes=$(canonical_device "$nodes") || return 0
 
 	# Can we find this node in crypttab
 	if ! node_is_in_crypttab "$nodes"; then
@@ -447,14 +446,12 @@ add_crypto_modules() {
 	#
 	#   d) /lib/modules/$VERSION/kernel/drivers/crypto/$specific-$mod.ko
 
-	if [ -e "$MODULESDIR/kernel/arch/" ]; then
-		for file in $(find "$MODULESDIR/kernel/arch/" -name "$mod-*.ko"); do
-			altmod="${file##*/}"
-			altmod="${altmod%.ko}"
-			manual_add_modules "$altmod"
-			found="yes"
-		done
-	fi
+	for file in $(find "$MODULESDIR/kernel/arch/" -name "$mod-*.ko"); do
+		altmod="${file##*/}"
+		altmod="${altmod%.ko}"
+		manual_add_modules "$altmod"
+		found="yes"
+	done
 
 	for file in $(find "$MODULESDIR/kernel/crypto/" -name "${mod}_generic.ko"); do
 		altmod="${file##*/}"
@@ -506,11 +503,9 @@ for dev in $rootdev $resumedevs; do
 	setup="yes"
 
 	if [ "$MODULES" = "most" ]; then
-		if [ -e "$MODULESDIR/kernel/arch" ]; then
-			archcrypto="$(find "$MODULESDIR/kernel/arch" -type d -name "crypto")"
-			if [ -n "$archcrypto" ]; then
-				copy_modules_dir "${archcrypto##*${MODULESDIR}/}"
-			fi
+		archcrypto="$(find "$MODULESDIR/kernel/arch" -type d -name "crypto")"
+		if [ -n "$archcrypto" ]; then
+			copy_modules_dir "${archcrypto##*${MODULESDIR}/}"
 		fi
 		copy_modules_dir "kernel/crypto"
 	else
