Update branch with current changes

diff --git a/debian/initramfs/cryptroot-script b/debian/initramfs/cryptroot-script
--- a/debian/initramfs/cryptroot-script
+++ b/debian/initramfs/cryptroot-script
@@ -42,10 +42,10 @@ message()
 udev_settle()
 {
 	# Wait for udev to be ready, see https://launchpad.net/bugs/85640
-	if [ -x /sbin/udevadm ]; then
-		/sbin/udevadm settle --timeout=30
-	elif [ -x /sbin/udevsettle ]; then
-		/sbin/udevsettle --timeout=30
+	if command -v udevadm >/dev/null 2>&1; then
+		udevadm settle --timeout=30
+	elif command -v udevsettle >/dev/null 2>&1; then
+		udevsettle --timeout=30
 	fi
 	return 0
 }
@@ -157,26 +157,6 @@ activate_vg()
 	return $?
 }
 
-activate_evms()
-{
-	local dev module
-
-	# Sanity checks
-	if [ ! -x /sbin/evms_activate ]; then
-		message "cryptsetup: evms_activate is not available"
-		return 1
-	fi
-
-	# Load modules used by evms
-	for module in dm-mod linear raid0 raid1 raid10 raid5 raid6; do
-		modprobe -q $module
-	done
-
-	# Activate it
-	/sbin/evms_activate
-	return $?
-}
-
 setup_mapping()
 {
 	local opts count cryptcreate cryptremove NEWROOT
@@ -204,7 +184,6 @@ setup_mapping()
 	# Make sure the cryptsource device is available
 	if [ ! -e $cryptsource ]; then
 		activate_vg
-		activate_evms
 	fi
 
 	# If the encrypted source device hasn't shown up yet, give it a
@@ -240,8 +219,8 @@ setup_mapping()
 
 	# We've given up, but we'll let the user fix matters if they can
 	while [ ! -e "${cryptsource}" ]; do
-		echo "	Check cryptopts=source= bootarg cat /proc/cmdline"
-		echo "	or missing modules, devices: cat /proc/modules ls /dev"
+		echo "	Check cryptopts=source= bootarg: cat /proc/cmdline"
+		echo "	or missing modules, devices: cat /proc/modules; ls /dev"
 		panic -r "ALERT!  ${cryptsource} does not exist.  Dropping to a shell!"
 	done
 
@@ -250,7 +229,7 @@ setup_mapping()
 	if [ "$cryptdiscard" = "yes" ]; then
 		cryptcreate="$cryptcreate --allow-discards"
 	fi
-	if /sbin/cryptsetup isLuks $cryptsource > /dev/null 2>&1; then
+	if /sbin/cryptsetup isLuks $cryptsource >/dev/null 2>&1; then
 		cryptcreate="$cryptcreate luksOpen $cryptsource $crypttarget"
 	else
 		cryptcreate="$cryptcreate -c $cryptcipher -s $cryptsize -h $crypthash create $crypttarget $cryptsource"
@@ -261,6 +240,7 @@ setup_mapping()
 	# Try to get a satisfactory password $crypttries times
 	count=0
 	while [ $crypttries -le 0 ] || [ $count -lt $crypttries ]; do
+		export CRYPTTAB_TRIED="$crypttries"
 		count=$(( $count + 1 ))
 
 		if [ $count -gt 1 ]; then
@@ -278,10 +258,12 @@ setup_mapping()
 		fi
 
 
-		if ! crypttarget="$crypttarget" cryptsource="$cryptsource" \
-		     $cryptkeyscript "$cryptkey" | $cryptcreate --key-file=- ; then
-			message "cryptsetup: cryptsetup failed, bad password or options?"
-			continue
+		if [ ! -e "$NEWROOT" ]; then
+			if ! crypttarget="$crypttarget" cryptsource="$cryptsource" \
+			     $cryptkeyscript "$cryptkey" | $cryptcreate --key-file=- ; then
+				message "cryptsetup: cryptsetup failed, bad password or options?"
+				continue
+			fi
 		fi
 
 		if [ ! -e "$NEWROOT" ]; then
@@ -289,11 +271,13 @@ setup_mapping()
 			return 1
 		fi
 
-		FSTYPE=''
-		eval $(fstype < "$NEWROOT")
+		#FSTYPE=''
+		#eval $(fstype < "$NEWROOT")
+		FSTYPE="$(/sbin/blkid -s TYPE -o value "$NEWROOT")"
 
 		# See if we need to setup lvm on the crypto device
-		if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
+		#if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
+		if [ "$FSTYPE" = "LVM_member" ] || [ "$FSTYPE" = "LVM2_member" ]; then
 			if [ -z "$cryptlvm" ]; then
 				message "cryptsetup: lvm fs found but no lvm configured"
 				return 1
@@ -303,15 +287,16 @@ setup_mapping()
 				return 1
 			fi
 
-			NEWROOT="/dev/mapper/$cryptlvm"
+			NEWROOT=${cmdline_root:-/dev/mapper/$cryptlvm}
 			if [ "$cryptrootdev" = "yes" ]; then
 				# required for lilo to find the root device
-				echo "ROOT=$NEWROOT" >> /conf/param.conf
+				echo "ROOT=$NEWROOT" >>/conf/param.conf
 			fi
 			eval $(fstype < "$NEWROOT")
 		fi
 
-		if [ -z "$FSTYPE" ] || [ "$FSTYPE" = "unknown" ]; then
+		#if [ -z "$FSTYPE" ] || [ "$FSTYPE" = "unknown" ]; then
+		if [ -z "$FSTYPE" ]; then
 			message "cryptsetup: unknown fstype, bad password or options?"
 			udev_settle
 			$cryptremove
@@ -336,17 +321,37 @@ setup_mapping()
 #
 
 # Do we have any kernel boot arguments?
-found=''
+cmdline_cryptopts=''
+unset cmdline_root
 for opt in $(cat /proc/cmdline); do
 	case $opt in
 	cryptopts=*)
-		found=yes
-		setup_mapping "${opt#cryptopts=}"
+		opt="${opt#cryptopts=}"
+		if [ -n "$opt" ]; then
+			if [ -n "$cmdline_cryptopts" ]; then
+				cmdline_cryptopts="$cmdline_cryptopts $opt"
+			else
+				cmdline_cryptopts="$opt"
+			fi
+		fi
+		;;
+	root=*)
+		opt="${opt#root=}"
+		case $opt in
+		/*) # Absolute path given. Not lilo major/minor number.
+			cmdline_root=$opt
+			;;
+		*) # lilo major/minor number (See #398957). Ignore
+		esac
 		;;
 	esac
 done
 
-if [ -n "$found" ]; then
+if [ -n "$cmdline_cryptopts" ]; then
+	# Call setup_mapping separately for each possible cryptopts= setting
+	for cryptopt in $cmdline_cryptopts; do
+		setup_mapping "$cryptopt"
+	done
 	exit 0
 fi
 
