pull in the latest uploads to the archive

diff --git a/luks/Makefile.am b/luks/Makefile.am
--- a/luks/Makefile.am
+++ b/luks/Makefile.am
@@ -2,7 +2,7 @@ moduledir = $(libdir)/cryptsetup
 
 noinst_LTLIBRARIES = libluks.la
 
-libluks_la_CFLAGS = -I sha
+libluks_la_CFLAGS = -I sha -Wall
 
 libluks_la_SOURCES = \
 	af.c \
@@ -124,6 +124,16 @@ test:
 	echo "key0" | ../src/cryptsetup -v luksOpen $(LOOPDEV) dummy 2>/dev/null 
 	@../src/cryptsetup -v remove dummy
 	@echo "success"
+
+# Non-Exclusive Open test
+	@echo Case: Non-Exclusive Open
+	echo "key0" | ../src/cryptsetup -v --readonly luksOpen $(LOOPDEV) dummy1 2>/dev/null
+# must fail
+	echo "key0" | ../src/cryptsetup -v --readonly luksOpen $(LOOPDEV) dummy2 2>/dev/null || true 
+	echo "key0" | ../src/cryptsetup -v --non-exclusive --readonly luksOpen $(LOOPDEV) dummy2 2>/dev/null
+	@../src/cryptsetup -v remove dummy1
+	@../src/cryptsetup -v remove dummy2
+
 
 # Key Slot 1 and key material section 1 must change, the rest must not
 	@echo Case: add key test for key files
