cryptsetup_1.0.5-2.dsc

diff --git a/debian/scripts/decrypt_opensc b/debian/scripts/decrypt_opensc
--- a/debian/scripts/decrypt_opensc
+++ b/debian/scripts/decrypt_opensc
@@ -9,58 +9,10 @@
 # Although opensc-tool --help reports that there is a --wait option, it doesn't
 # seem to be implemented.
 
-check_middleware() {
-    # Probe reader drivers to ensure opensc installation works (should output
-    # errors if opensc is not capable of reading cards)
-    opensc-tool -R >/dev/null
-    # Unfortunately "opensc-tool -R" tests for the presence of a reader rather
-    # than simply listing the reader drivers available, so don't abort
-    #if [ $? != 0 ] ; then
-    #    echo Smart Card Middleware broken! >&2
-    #    exit 1
-    #fi
-}
-
-check_reader() {
-    readerfound=0
-
-    if [ ! -e "$readertmp" ] ; then
-        readertmp=$(mktemp /tmp/decrypt_opensc.XXXXXXXX)
-    fi
-
-    opensc-tool -l > $readertmp 2>&1
-    if [ $? == 0 ] ; then
-        readerfound=1
-    fi
-}
-
-wait_reader() {
-    check_reader
-    if [ $readerfound == 0 ] ; then
-        echo Waiting for Smart Card reader... >&2
-        tries=0
-        while [ $readerfound == 0 -a $tries -lt 60 ] ; do
-            sleep 1
-            check_reader
-            tries=$(($tries + 1))
-        done
-        cat $readertmp >&2
-        if [ $readerfound == 0 ] ; then
-            echo Failed to find Smart Card reader!
-            exit 1
-        fi
-    fi
-    rm $readertmp
-}
-
 check_card() {
     cardfound=0
 
-    if [ ! -e "$cardtmp" ] ; then
-        cardtmp=$(mktemp /tmp/decrypt_opensc.XXXXXXXX)
-    fi
-
-    opensc-tool -n > $cardtmp 2>&1
+    cardtmp=$(/usr/bin/opensc-tool -n 2>&1)
     if [ $? == 0 ] ; then
         cardfound=1
     fi
@@ -69,25 +21,27 @@ check_card() {
 wait_card() {
     check_card
     if [ $cardfound == 0 ] ; then
-        echo Waiting for Smart Card... >&2
+        echo "Waiting for Smart Card..." >&2
         tries=0
         while [ $cardfound == 0 -a $tries -lt 60 ] ; do
             sleep 1
             check_card
-            #tries=$(($tries + 1))
+            tries=$(($tries + 1))
         done
-        cat $cardtmp >&2
         if [ $cardfound == 0 ] ; then
-            echo Failed to find Smart Card card!
+            echo 'Failed to find Smart Card card!' >&2
             exit 1
         fi
     fi
-    rm $cardtmp
 }
 
-echo >&2
-check_middleware
-wait_reader
 wait_card
-pkcs15-crypt --decipher --input $1 --pkcs1 --raw
+if [ -p /dev/.initramfs/usplash_outfifo ] && [ -x /sbin/usplash_write ]; then
+	# Get pin number from usplash
+	/sbin/usplash_write "INPUTQUIET Enter pin for $crypttarget ($cryptsource): "
+	/usr/bin/pkcs15-crypt --decipher --input $1 --pkcs1 --raw --pin "$(cat /dev/.initramfs/usplash_outfifo)"
+else
+	# Get pin number from console
+	/usr/bin/pkcs15-crypt --decipher --input $1 --pkcs1 --raw < /dev/console 2> /dev/console
+fi
 exit $?
